# 1.Print 'Hello HCIA'.

In [1]:
print("Print 'Hello HCIA")

Print 'Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a, b = 5, 10
a + b

15

# 3.Define a list and replicate in three different ways.

In [6]:
original_list = [1, 2, 3, 4]
duplicate_list1 = original_list[:]
duplicate_list2 = list(original_list)

import copy
duplicate_list3 = copy.copy(original_list)

[1, 2, 3, 4]


# 4.Define two lists and merge them together.

In [7]:
list1 = [1, 5, 6]
list2 = [2, 4, 5, 7]
list1 + list2

[1, 5, 6, 2, 4, 5, 7]

# 5. Get the last element of the list and print it.

In [9]:
list1 = [2, 6, 7, 8, 0]

print(list1[-1])

0


# 6.Define a tuple that contains only one element.

In [12]:
a = (1,)

# 7.Define a three-line long string.

In [13]:
long_string = """first_line
second_list
third_line"""

first_line
second_list
third_line


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [14]:
a = ("hello ", "new ", "world",)
for element in a:
    print(element)

hello 
new 
world


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [15]:
def Mul(a, b):
    return a * b

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [22]:
import numpy

arr = numpy.array([[0 for i in range(5)] for j in range(5)])

(5, 5)


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [24]:
import numpy

arr = numpy.array([[0 for i in range(6)] for j in range(4)])

(4, 6)
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [27]:
import numpy

arr = numpy.arange(15)

arr = arr.reshape(3, 5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [42]:
import numpy

A = numpy.arange(6).reshape(3,2)
B = numpy.arange(8).reshape(4, 2)

print(A[2, 0] * B[2, 1])

20
